"""Repository identity matching and component-name propagation.

A component's authored name is presentation metadata. Capture matching is based
on durable locator identity so renaming an object cannot cause the next capture
of that same runtime control to create a duplicate repository entry.
"""
from __future__ import annotations

from dataclasses import replace
from typing import Any, Mapping

from automation_harness.core.component_repository import ComponentRepository
from automation_harness.models.component import CapturedComponent, ComponentDefinition
from automation_harness.models.plan import StepCall, TestPlan
from automation_harness.core.solipsys_identity import locators_match, strategy_parts


_ID_KEYS = frozenset({"id", "accessible_id"})
_TEXT_KEYS = frozenset({"text", "accessible_text", "name"})
_SCOPE_KEYS = frozenset({"window", "application"})
_STRONG_KEYS = frozenset({
    "id", "accessible_id", "properties", "user_data", "name",
    "accessible_text", "text", "component_path",
    # Durable semantic identity emitted by the Java agent for objects rendered
    # inside opaque Solipsys canvases. Runtime refs and geometry are excluded.
    "track_identity_value", "track_identity_key", "track_class", "rendered_class",
})


def find_existing_component_ids(
    repository: ComponentRepository,
    captured: CapturedComponent,
) -> tuple[str, ...]:
    """Return existing components whose durable locator matches ``captured``.

    The repository component_id is intentionally ignored. An object that was
    renamed from an autogenerated name to a user-authored name must still match
    a later capture of the same live component.
    """
    result: list[str] = []
    capture_strategy = captured.candidate_strategy()
    capture_identity = _strategy_identity(capture_strategy.options)
    capture_values = _capture_values(captured, capture_identity)

    for component_id, definition in repository.components.items():
        if definition.framework and captured.framework and definition.framework != captured.framework:
            continue
        if (
            definition.object_type.value != "custom"
            and captured.semantic_type().value != "custom"
            and definition.object_type != captured.semantic_type()
        ):
            continue
        if any(_strategy_matches_capture(strategy, capture_strategy, capture_values)
               for strategy in definition.strategies):
            result.append(component_id)
    return tuple(result)


def _strategy_matches_capture(strategy, capture_strategy, capture_values):
    if strategy.type != capture_strategy.type:
        return False
    if strategy.type == "java_agent":
        expected_mandatory, expected_assistive = strategy_parts(strategy.options)
        actual_mandatory, actual_assistive = strategy_parts(capture_strategy.options)
        if "track_identity_key" in expected_mandatory or "track_identity_key" in actual_mandatory:
            return locators_match(
                expected_mandatory, expected_assistive,
                actual_mandatory, actual_assistive,
            )
    return _identity_matches(_strategy_identity(strategy.options), capture_values)


def rename_repository_component(
    repository: ComponentRepository,
    old_component_id: str,
    new_component_id: str,
) -> ComponentRepository:
    if old_component_id == new_component_id:
        return repository
    return repository.rename(old_component_id, new_component_id)


def rename_plan_component(plan: TestPlan, old_component_id: str, new_component_id: str) -> TestPlan:
    """Rewrite component references while preserving immutable object identity."""
    if old_component_id == new_component_id:
        return plan

    steps = tuple(_rename_step(step, old_component_id, new_component_id) for step in plan.steps)
    objects = dict(plan.objects)
    if old_component_id in objects:
        value = objects.pop(old_component_id)
        if new_component_id in objects and objects[new_component_id] != value:
            raise ValueError("inline plan object %r already exists" % new_component_id)
        objects[new_component_id] = value

    step_definitions = _rewrite_component_refs(plan.step_definitions, old_component_id, new_component_id)
    return replace(plan, steps=steps, objects=objects, step_definitions=step_definitions)


def readable_plan_component_references(
    plan: TestPlan,
    repository: ComponentRepository,
) -> TestPlan:
    """Migrate UUID object references to their readable repository aliases.

    Repository ``object_id`` values remain the durable identity used to detect
    rename and reparent operations. Test Plans are authored artifacts, however,
    and their component references must remain comprehensible without looking
    up UUIDs in the repository.
    """
    current = plan
    for definition in repository.components.values():
        current = rename_plan_component(
            current,
            definition.object_id,
            definition.component_id,
        )
    return current


def _rename_step(step: StepCall, old: str, new: str) -> StepCall:
    return replace(
        step,
        inputs=_rewrite_component_refs(step.inputs, old, new),
        completion=_rewrite_component_refs(step.completion, old, new),
        scope=_rewrite_component_refs(step.scope, old, new),
    )


def _rewrite_component_refs(value: Any, old: str, new: str, *, field: str | None = None) -> Any:
    if isinstance(value, Mapping):
        result = {}
        for key, item in value.items():
            key_text = str(key)
            result[key] = _rewrite_component_refs(item, old, new, field=key_text)
        return result
    if isinstance(value, tuple):
        return tuple(_rewrite_component_refs(item, old, new, field=field) for item in value)
    if isinstance(value, list):
        return [_rewrite_component_refs(item, old, new, field=field) for item in value]
    if isinstance(value, str) and value == old and field in {
        "component_id", "component", "object", "object_name", "owner_component_id",
    }:
        return new
    return value


def _strategy_identity(options: Mapping[str, Any] | None) -> dict[str, Any]:
    if not isinstance(options, Mapping):
        return {}
    raw = options.get("identification", options)
    if not isinstance(raw, Mapping):
        return {}
    mandatory = raw.get("mandatory", raw)
    assistive = raw.get("assistive", {})
    result: dict[str, Any] = {}
    if isinstance(mandatory, Mapping):
        result.update(mandatory)
    if isinstance(assistive, Mapping):
        for key, value in assistive.items():
            result.setdefault(key, value)
    return result


def _capture_values(captured: CapturedComponent, identity: Mapping[str, Any]) -> dict[str, Any]:
    result = dict(identity)
    if captured.accessible_id:
        result.setdefault("id", captured.accessible_id)
        result.setdefault("accessible_id", captured.accessible_id)
    if captured.name:
        result.setdefault("name", captured.name)
        result.setdefault("text", captured.name)
        result.setdefault("accessible_text", captured.name)
    if captured.role:
        result.setdefault("role", captured.role)
        result.setdefault("accessible_role", captured.role.replace(" ", "_").upper())
    if captured.window:
        result.setdefault("window", captured.window)
    if captured.application:
        result.setdefault("application", captured.application)
    if captured.native_class:
        result.setdefault("class", captured.native_class)
    return result


def _identity_matches(expected: Mapping[str, Any], captured: Mapping[str, Any]) -> bool:
    if not expected:
        return False

    compared = 0
    strong = False
    for key, expected_value in expected.items():
        if key in {"style_classes", "ordinal"}:
            continue
        actual, present = _lookup_capture_value(captured, key)
        if not present:
            # Identity reuse is a destructive decision: a missing condition is
            # not evidence that two captures refer to the same live object.
            return False
        compared += 1
        if not _value_equal(actual, expected_value):
            return False
        if key in _STRONG_KEYS:
            strong = True

    # Never deduplicate from class/role/window coincidence alone. At least one
    # semantic identity value must agree.
    return compared > 0 and strong


def _lookup_capture_value(captured: Mapping[str, Any], key: str) -> tuple[Any, bool]:
    if key in _ID_KEYS:
        for alias in _ID_KEYS:
            if alias in captured and captured[alias] not in (None, ""):
                return captured[alias], True
        return None, False
    if key in _TEXT_KEYS:
        for alias in (key, "accessible_text", "text", "name"):
            if alias in captured and captured[alias] not in (None, ""):
                return captured[alias], True
        return None, False
    if key in _SCOPE_KEYS:
        for alias in (key, "window", "application"):
            if alias in captured and captured[alias] not in (None, ""):
                return captured[alias], True
        return None, False
    return (captured[key], True) if key in captured else (None, False)


def _value_equal(left: Any, right: Any) -> bool:
    if isinstance(left, Mapping) and isinstance(right, Mapping):
        return all(key in left and _value_equal(left[key], value) for key, value in right.items())
    if isinstance(left, str) and isinstance(right, str):
        return left == right
    return left == right
